
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nihaal Y K",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <>
    <body className="bg-neutral-950">
      <nav className="fixed inset-x-0 bottom-0 text-center rounded-full mx-10 my-6 py-2 px-8 bg-gray-dark-500 transition hover:bg-gray-700 text-white">
        <div className="max-w-6xl mx-auto flex justify-between">
		<svg  xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="cyan" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart hover:stroke-red-500 delay-150 transition "><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
          <a className="transition ease-in-out delay-50  hover:-translate-z-1 hover:scale-110 hover:text-red-500 duration-50" href="/post/id:contact">Home</a>
          <a className="transition ease-in-out delay-50  hover:-translate-z-1 hover:scale-110 hover:text-red-500 duration-50" href="/about">About</a>
          <a className="transition ease-in-out delay-50  hover:-translate-z-1 hover:scale-110 hover:text-red-500 duration-50" href="/contact">Contact</a>
          <a className="transition ease-in-out delay-50  hover:-translate-z-1 hover:scale-110 hover:text-red-500 duration-50" href="/post">Post</a>
          <a className="transition ease-in-out delay-50  hover:-translate-z-1 hover:scale-110 hover:text-red-500 duration-50" href="./contact">Post 1</a>
        </div>
      </nav>
      </body>
    </>
        
        {children}
        </body>
    </html>
  );
}
